# Generated by Django 2.0.2 on 2018-05-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tape', models.CharField(max_length=1000)),
                ('iteration', models.IntegerField()),
                ('state', models.CharField(max_length=3)),
                ('task', models.CharField(max_length=100)),
            ],
        ),
    ]
