# Generated by Django 2.0.2 on 2018-05-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='head_position',
            field=models.IntegerField(default=0),
        ),
    ]
