# Generated by Django 2.0.2 on 2018-05-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_auto_20180519_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
